ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TruvideoReactTurboVideoSdkExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  pre_install do |installer|
    system("cd ../../ && npx bob build --target codegen")
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    fmt_format_inl = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'format-inl.h')
    if File.exist?(fmt_format_inl)
      contents = File.read(fmt_format_inl)
      patched = contents
        .gsub('fmt::format_to(it, FMT_STRING("{}{}"), message, SEP);', 'fmt::format_to(it, "{}{}", message, SEP);')
        .gsub('fmt::format_to(it, FMT_STRING("{}{}"), ERROR_STR, error_code);', 'fmt::format_to(it, "{}{}", ERROR_STR, error_code);')
        .gsub('fmt::format_to(out, FMT_STRING("{:x}"), value);', 'fmt::format_to(out, "{:x}", value);')
        .gsub('fmt::format_to(out, FMT_STRING("{:08x}"), value);', 'fmt::format_to(out, "{:08x}", value);')
        .gsub(%(fmt::format_to(out, FMT_STRING("p{}"),\n                           n.exp_ * detail::bigint::bigit_bits);), %(fmt::format_to(out, "p{}", n.exp_ * detail::bigint::bigit_bits);))

      File.write(fmt_format_inl, patched) if patched != contents
    end
  end
end
